version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: backend
    command: npm start
    ports:
      - 3001:3001
    volumes:
      - ./backend/:/app/
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json   
    networks:
      - backend-frontend
      - database-backend
    depends_on:
      - database    
  database:
    container_name: database 
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    expose:
      - "3306"
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - database-backend  
    environment:
      - MYSQL_DATABASE=buechereiverwaltung
      - MYSQL_ROOT_PASSWORD=testpassword12
  frontend:
    container_name: frontend
    build:
      context: frontend
    command: npm start  
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json   
    networks:
      - backend-frontend
    depends_on:
      - backend

networks:
  backend-frontend:
  database-backend:      
volumes:
  db-data:    
