version: '3.8'

services:         
  database:
    container_name: database 
    # mariadb image supports both amd64 & arm64 architecture & stays open source
    image: mysql:5.7
    # mysql
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - 3002:3306
    # no volume mount on host
    volumes:
      - db-data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_DATABASE=buechereiverwaltung
      - MYSQL_ROOT_PASSWORD=testpassword12
  frontend:
    container_name: frontend
    build:
      context: frontend
    command: npm start  
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json   
    depends_on:
      - database

volumes:
  db-data:    
